export default {
  p1_bg: require('../img/p1/p1.jpg'),
  p1_tv: require('../img/p1/p1_tv_rect.png'),
  p1_pic: require('../img/p1/p1_tv_pic.png'),

  p2_bg: require('../img/p2/p2.jpg'),
  p2_ball: require('../img/p2/ball.png'),
  goalkeeper: require('../img/p2/goalkeeper.png'),
  ma1: require('../img/p2/ma1.png'),
  ma2: require('../img/p2/ma2.png'),
  p2_title: require('../img/p2/p2_title.png'),
  p2_text: require('../img/p2/p2_text.png'),
  p2_year: require('../img/p2/p2_year.png'),

  p3_bg: require('../img/p3/p3.jpg'),
  p3_child: require('../img/p3/p3_child.png'),
  p3_dad: require('../img/p3/p3_dad.png'),
  p3_title: require('../img/p3/p3_title.png'),
  p3_text: require('../img/p3/p3_text.png'),
  p3_year: require('../img/p3/p3_year.png'),
  p3_ball: require('../img/p3/p3_ball.png'),
  p3_tv: require('../img/p3/p3_tv_rect.png'),
  p3_tv_cover: require('../img/p3/p3_tv_cover.png'),

  p4_bg: require('../img/p4/p4.jpg'),
  beckham: require('../img/p4/beckham.png'),
  mouthopen: require('../img/p4/mouth_open.png'),
  mouthclose: require('../img/p4/mouth_close.png'),
  p4_hand: require('../img/p4/p4_hand.png'),
  p4_people: require('../img/p4/p4_people.png'),
  p4_title: require('../img/p4/p4_title.png'),
  p4_text: require('../img/p4/p4_text.png'),
  p4_year: require('../img/p4/p4_year.png'),

  p5_bg: require('../img/p5/p5.jpg'),
  p5_title: require('../img/p5/p5_title.png'),
  p5_text: require('../img/p5/p5_text.png'),
  p5_year: require('../img/p5/p5_year.png'),
  p5_people: require('../img/p5/p5_people.png'),
  p5_mouth_open: require('../img/p5/p5_mouth_open.png'),
  p5_mouth_close: require('../img/p5/p5_mouth_close.png'),

  p6_bg: require('../img/p6/p6.jpg'),
  p6_title: require('../img/p6/p6_title.png'),
  p6_text: require('../img/p6/p6_text.png'),
  p6_text_bg: require('../img/p6/p6_text_bg.png'),
  p6_year: require('../img/p6/p6_year.png'),
  p6_mouth_open: require('../img/p6/p6_mouth_open.png'),
  p6_mouth_close: require('../img/p6/p6_mouth_close.png'),
  team: require('../img/p6/team.png'),

  p7_bg: require('../img/p7/p7.jpg'),
  p7_title: require('../img/p7/p7_title.png'),
  p7_text: require('../img/p7/p7_text.png'),
  p7_year: require('../img/p7/p7_year.png'),
  p7_dad: require('../img/p7/p7_dad.png'),
  p7_child: require('../img/p7/p7_child.png'),
  p7_moutai: require('../img/p7/p7_moutai.png'),
  p7_tv: require('../img/p7/p7_tv_rect.png'),
  p7_tv_cover: require('../img/p7/p7_tv_cover.png'),
  
  p8_bg: require('../img/p8/p8.jpg'),
  p8_title: require('../img/p8/p8_title.png'),
  p8_text: require('../img/p8/p8_text.png'),
  p8_year: require('../img/p8/p8_year.png'),
  p8_people: require('../img/p8/p8_people.png'),
  zidane: require('../img/p8/zidane.png'),

  p9_bg: require('../img/p9/p9.jpg'),
  p9_title: require('../img/p9/p9_title.png'),
  p9_text: require('../img/p9/p9_text.png'),
  p9_year: require('../img/p9/p9_year.png'),
  p9_dad: require('../img/p9/p9_dad.png'),
  p9_child: require('../img/p9/p9_child.png'),
  p9_scene2: require('../img/p9/p9_scene2.png'),
  p9_tv_cover: require('../img/p9/p9_tv_cover.jpg'),

  p10_bg: require('../img/p10/p10.jpg'),
  p10_title: require('../img/p10/p10_title.png'),
  p10_text: require('../img/p10/p10_text.png'),
  p10_year: require('../img/p10/p10_year.png'),
  p10_ball: require('../img/p10/p10_ball.png'),
  klose: require('../img/p10/klose.png'),

  p11_bg: require('../img/p11/p11.jpg'),
  p11_title: require('../img/p11/p11_title.png'),
  p11_text: require('../img/p11/p11_text.png'),
  p11_year: require('../img/p11/p11_year.png'),
  p11_ball: require('../img/p11/p11_ball.png'),
  p11_child: require('../img/p11/p11_child.png'),
  p11_dad: require('../img/p11/p11_dad.png'),
  p11_grandpa: require('../img/p11/p11_grandpa.png'),
  p11_potted: require('../img/p11/p11_potted.png'),
  p11_table: require('../img/p11/p11_table.png'),

  p12_bg: require('../img/p12/p12.jpg'),
  p12_text: require('../img/p12/p12_text.png'),
  p12_year: require('../img/p12/p12_year.png'),
  // p12_people: require('../img/p12/p12_people.png'),
  p12_people1: require('../img/p12/p12_people1.png'),
  p12_people2: require('../img/p12/p12_people2.png'),
  p12_table: require('../img/p12/p12_table.png'),

  p13_btn_home: require('../img/p13/btn_home.png'),
  p13_btn_replay: require('../img/p13/btn_replay.png'),
  p13_btn_share: require('../img/p13/btn_share.png'),
  p13_text1: require('../img/p13/p13_text1.png'),
  p13_text2: require('../img/p13/p13_text2.png'),
  p13_text3: require('../img/p13/p13_text3.png'),
  p13_logo: require('../img/p13/p13_logo.png'),

  tip_hand: require('../img/tip/tip_hand.png'),
  tip_circle: require('../img/tip/tip_circle.png'),
  tip_wx: require('../img/tip/tip_share.png'),
  tip_arrow_left: require('../img/tip/arrow_left.png'),
  tip_arrow_right: require('../img/tip/arrow_right.png'),

  lock_phone: require('../img/tip/lock.png')
}